title: Richard Wolf
description: Psychotherapeut in Ausbildung unter Supervision
email: your@email.com
baseurl: "" # leave this empty unless you're in a subfolder
url: "https://happytraum.github.io/tellname/"

# Build settings
markdown: kramdown
theme: null
