url: https://richardwolf.co.at
title: Richard Wolf
description: Psychotherapeut in Ausbildung unter Supervision
email: your@email.com
baseurl: "" # leave this empty unless you're in a subfolder
# url: "https://happytraum.github.io/tellname/"
description: "Richard Wolf Psychotherapie Wien 1170 Hernals Trauma traumasensibel in ausbildung unter Supervision humanistisch personzentriert"
# Adresse
address:
  - line: Diepoldplatz
  - line: 1170 Wien
# Build settings
markdown: kramdown
theme: null
